### ISSUE TITLE
Pages, that got renamed still get exported with the old URL

### ISSUE THREAD

**Issue by TheKeymaster** [howard/dokuwiki2findologic#1]
The title says everything.
But here is an example:

2.2.2011 Created DokuWiki article: "Test132"
2.3.2011 Renamded DokuWiki article, because of a naming issue: "Test123"

Export still exports "Test132" instead of "Test123".

**Comment by howard** [comment]
@TheKeymaster I fixed it, but the export for your project is not live yet. Approach me tomorrow so I can update it for you.
