### ISSUE TITLE
The Description Text always begins with " 'b "

### ISSUE THREAD

**Issue by TheKeymaster** [howard/dokuwiki2findologic#2]
Title says everything.
Example:
"b'Im Folgenden ist eine Auflistung der einzelnen FINDOLOGIC Direct Integration Module, mit den entsprechend exportierten Feldern. \n\n\n\nMatrix\n Magento (not yet released) OXID (beta) Shopware (not yet released) Funktionen Suche \xe2\x9c\x93 \xe2\x9c\x93 \xe2\x9c\x93 Navigation \xe2\x9c\x93 \xe2\x9c\x93 \xe2\x9c\x93 Tracking \xe2\x9c\x93 \xe2\x9c\x93 \xe2\x9c\x93 Attribute (Filter) Kategorien \xe2\x9c\x93 \xe2\x9c\x93 \xe2\x9c\x93 Hersteller \xe2\x9c\x93 \xe2\x9c\x93 \xe2\x9c\x93 Preis \xe2\x9c\x93 \xe2\x9c\x93 \xe2\x9c\x93 Varianten-Attribute \xe2\x9c\x93 \xe2\x9c\x93 \xe2\x9c\x93 Artikel-Eigenschaften \xe2\x9c\x93 - \xe2\x9c\x93 Bewertungen \xe2\x9c\x93 \xe2\x9c\x93 \xe2\x9c\x93 Angebote \xe2\x9c\x93 \xe2\x9c\x93 \xe2\x9c\x93 Neuheiten \xe2\x9c\x93 - \xe2\x9c\x93 Versandkostenfrei - - \xe2\x80\xa6'"

**Comment by howard** [comment]
@TheKeymaster I fixed it, but the export for your project is not live yet. Approach me tomorrow so I can update it for you.
