### ISSUE TITLE
Articles get exported with the create date instead of the lastest edit date

### ISSUE THREAD

**Issue by TheKeymaster** [howard/dokuwiki2findologic#3]
I will try to explain that with a example:
Create Date: 2.2.2011
Updated yesterday: 26.07.2016
If this gets exported and I try to sort by newest, I won't get this article. Or just at the end because some articles got created later. (If this was the first article, that got created)
:octopus:

**Comment by howard** [comment]
@TheKeymaster I implemented it, but the export for your project is not live yet. Approach me tomorrow so I can update it for you.
