### ISSUE TITLE
Integrator-sites get exported

### ISSUE THREAD

**Issue by TheKeymaster** [howard/dokuwiki2findologic#4]
Generally; Integration-sites get exported too. Like fl:integrators:verysecure:verysecure
Fix this asap,
Thanks :)

**Comment by TheKeymaster** [comment]
Here also is a Screenshot for that
![screen](https://cloud.githubusercontent.com/assets/20555112/17323229/b116c978-58a1-11e6-85a4-19056a01e0e7.png)

**Comment by TheKeymaster** [comment]
![screen](https://cloud.githubusercontent.com/assets/20555112/17323268/d3486d80-58a1-11e6-8e04-588076e10f42.png)
There is an example for that. :cake:

**Comment by howard** [comment]
This is a usage error where the flag `--exclude fl:integrators` was omitted. I will generate the corrected export tomorrow.

**Comment by howard** [comment]
@TheKeymaster It would help a lot if you provided me with a post-it containing all prefixes that should not be exported tomorrow.
