### ISSUE TITLE
I would prefer to take the title from the 1st word of the page

### ISSUE THREAD

**Issue by TheKeymaster** [howard/dokuwiki2findologic#5]
Umm.. not the first word. Again here a screenshot :dancers: :D
![hax](https://cloud.githubusercontent.com/assets/20555112/17336045/bd90c998-58dc-11e6-85ab-f04d88602407.png)

**Comment by TheKeymaster** [comment]
For the Smart Suggest

**Comment by howard** [comment]
@TheKeymaster I imported the updated export. Let me know how titles work for you. If there are problems, I'll re-open the issue.
